
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='aws-sso-lib',
    version='1.15.0-dev',
    description='Library to make AWS SSO easier',
    python_requires='==3.*,>=3.7.0',
    project_urls={"homepage": "https://github.com/benkehoe/aws-sso-util/blob/master/lib/README.md", "repository": "https://github.com/benkehoe/aws-sso-util"},
    author='Ben Kehoe',
    author_email='ben@kehoe.io',
    license='Apache-2.0',
    classifiers=['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'License :: OSI Approved :: Apache Software License', 'Operating System :: OS Independent', 'Topic :: Utilities', 'Topic :: Software Development :: Libraries'],
    packages=['aws_sso_lib', 'aws_sso_lib.vendored_botocore'],
    package_dir={"": "."},
    package_data={},
    install_requires=['aws-error-utils==2.*,>=2.4.0', 'boto3<2.0.0,>=1.24.60'],
    extras_require={"dev": ["mypy==0.*,>=0.931.0", "pylint==2.*,>=2.5.2", "types-python-dateutil==2.*,>=2.8.7"]},
)
